# ████████╗███████╗███╗░░░███╗██████╗░███████╗░██████╗████████╗
# ╚══██╔══╝██╔════╝████╗░████║██╔══██╗██╔════╝██╔════╝╚══██╔══╝
# ░░░██║░░░█████╗░░██╔████╔██║██████╔╝█████╗░░╚█████╗░░░░██║░░░
# ░░░██║░░░██╔══╝░░██║╚██╔╝██║██╔═══╝░██╔══╝░░░╚═══██╗░░░██║░░░
# ░░░██║░░░███████╗██║░╚═╝░██║██║░░░░░███████╗██████╔╝░░░██║░░░
# ░░░╚═╝░░░╚══════╝╚═╝░░░░░╚═╝╚═╝░░░░░╚══════╝╚═════╝░░░░╚═╝░░░

# Anti-Leak Protection
LICENSE: ""

Spawn:
  X: 0
  Y: 100
  Z: 0
  Pitch: 0
  Yaw: 0

WORLD:
  WEATHER: false
  MOBS: false
  BLOCKS:
    PLACE: false
    BREAK: false