# ████████╗███████╗███╗░░░███╗██████╗░███████╗░██████╗████████╗
# ╚══██╔══╝██╔════╝████╗░████║██╔══██╗██╔════╝██╔════╝╚══██╔══╝
# ░░░██║░░░█████╗░░██╔████╔██║██████╔╝█████╗░░╚█████╗░░░░██║░░░
# ░░░██║░░░██╔══╝░░██║╚██╔╝██║██╔═══╝░██╔══╝░░░╚═══██╗░░░██║░░░
# ░░░██║░░░███████╗██║░╚═╝░██║██║░░░░░███████╗██████╔╝░░░██║░░░
# ░░░╚═╝░░░╚══════╝╚═╝░░░░░╚═╝╚═╝░░░░░╚══════╝╚═════╝░░░░╚═╝░░░

# Anti-Leak Protection
LICENSE: ""

PROVIDERS:
  SCOREBOARD: true

Spawn:
  X: 0
  Y: 100
  Z: 0
  Pitch: 0
  Yaw: 0

JOIN-SOUND:
  ENABLED: true
  SOUND: "CAT_MEOW"

JOIN-SPEED:
  ENABLED: true
  VALUE: 4

WORLD:
  WEATHER: false
  MOBS: false
  DAMAGE: false
  BLOCKS:
    PLACE: false
    BREAK: false

ANTI-VOID:
  ENABLED: true
  LIMIT: 0

BLOCKED-COMMANDS:
  ENABLED: true
  NO-PERMISSION: "&cYou don't have permission to do this command!"
  LIST:
    - pl
    - plugins
    - ver
    - version
    - about
    - icanhasbukkit
    - bukkit:?